### ISSUE TITLE
multi-setting votes do not work

### ISSUE THREAD

**Issue by CommunistSpectator** [wetfish/teeworlds#7]
when voting to change map+scorelimit+maxplayers, vote only changes map.

I think two of the sttings (map and gametype) require a map reload, and sowhen one is executed, the rest of the command is truncated. technically a problem with tw derver, but the result is broken vote buttons on wetfish servers

**Comment by itsrachelfish** [comment]
Would it be possible to change the order of the commands, so the map is the last thing changed?

**Comment by PathosEthosLogos** [comment]
You have to use semicolons to use multiple commands in one line.

Alternative is to make a config file and use "exec" command to execute that config file.

**Comment by CommunistSpectator** [comment]
i think having to reload the map 2x is anissue, and running a pair of scripts to ensure both settings are changed is the clearest solution (unless someone updates server to change settings with only one map reload)

**Comment by PathosEthosLogos** [comment]
Like I said, you can use semicolon:

change_map dm1; sv_scorelimit 9001; sv_spectator_slots 2

This way, you can have three commands executed in one line. This is one vote, so using vote, it would be:

add_vote "DM1, 9001 score, 14 players" "change_map dm1; sv_scorelimit 9001; sv_spectator_slots 2"

**Comment by CommunistSpectator** [comment]
it forces the map to reload, and truncates the end of the line. the fix in my fork is clean enough.

**Comment by itsrachelfish** [comment]
@PathosEthosLogos that's how it was defined in the votes already. The pull request submitted by @CommunistSpectator uses exec as you suggested, which fixed the issue.
